version: '3'
services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      - DB_URL=postgresql://postgres:postgres@db/your_database
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=your_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
