version: '3.8'

services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/app
    environment:
     - FLASK_ENV=development
     - APP_FILE=app.py
     - FLASK_RUN_HOST=0.0.0.0
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: postgres
     
